baseURL = 'https://www.supuwoerc.xyz/'
languageCode = 'zh-cn'
title = 'Salud'

# å¯ç”¨ä¸»é¢˜
theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
paginate = 5
enableGitInfo = true

[params]
author = 'zhangqm'
slogan = 'ä¸è¦æ¸©å’Œåœ°èµ°è¿›é‚£ä¸ªè‰¯å¤œ'

# é¡µé¢è¯­è¨€ï¼Œé»˜è®¤ä¸­æ–‡
en = false

# æ¿€æ´»æš—è‰²æ¨¡å¼ï¼Œ
# ç”±äºé™æ€é¡µé¢çš„é™åˆ¶ï¼Œæˆ‘ä»¬ä½¿ç”¨æµè§ˆå™¨æœ¬åœ°å­˜å‚¨æ¥è®°å¿†è¯¥çŠ¶æ€ï¼Œ
# å¦‚æœè®¾ç½®ä¸º `true` åï¼Œé»˜è®¤ä¸æ˜¯æš—è‰²æ¨¡å¼ï¼Œæ¸…é™¤æµè§ˆå™¨ç¼“å­˜ååˆ·æ–°é¡µé¢å³å¯
dark = true

# æ–‡ç« åˆ—è¡¨é¡µå•åˆ—æ˜¾ç¤º
isSingleColumnOfPostList = true

# æ¿€æ´»é¡µé¢åŠ è½½æ—¶çš„è¿‡æ¸¡åŠ¨ç”»
hasActiveAnimate = true

# æ¿€æ´» cool æ¨¡å¼ï¼Œé…·çˆ½ä½†æ˜¯æ¶ˆè€—èµ„æºä¹Ÿæ›´å¤šï¼Œ
# å¦‚æœæƒ³æ›´æ¢é¡µé¢èƒŒæ™¯ï¼Œåªéœ€è¦å°†å›¾ç‰‡å‘½åä¸º `default.jpg` åï¼Œç½®äº `/static/imgs/bg` æ–‡ä»¶å¤¹ä¸­å³å¯ï¼Œ
# æµè§ˆå™¨æœ‰ç¼“å­˜ï¼Œæ›´æ¢åå¼ºåˆ¶é¡µé¢åˆ·æ–°ï¼ˆå¿«æ·é”®ä¸º Ctrl+Shift+Rï¼‰ä¸€ä¸‹å³å¯
hasActiveCool = false

# å±•å¼€/æŠ˜å ä»£ç å—ï¼Œé»˜è®¤ä¸æŠ˜å ï¼Œ
# è®¾ç½®ä¸º `true` ï¼Œåˆ™é»˜è®¤æŠ˜å æ‰€æœ‰ä»£ç å—ï¼Œ
# æç¤ºï¼Œåœ¨ç§»åŠ¨è®¾å¤‡ä¸­ï¼Œç³»ç»Ÿè®¾ç½®ä¸ºæ°¸ä¹…æŠ˜å ä»£ç å—
# ï¼ˆè¯¥é¡¹è®¾ç½®ä¸é‡è¦ï¼Œå®Œå…¨æ˜¯ä¸ªäººå–œå¥½ï¼‰
hasFoldAllCodeBlocks = false

# å¦‚ä¸‹å¯¼èˆªé“¾æ¥ï¼Œä½ åº”è¯¥åˆ›å»ºå¯¹åº”çš„ `.md` æ–‡ä»¶ï¼Œä»¥ç”Ÿæˆå¯¹åº”çš„é¡µé¢
# -----------------------------------
# Nav - nav.md or nav/index.md 
# Search - search.md or search/index.md
# Archive - archive.md or archive/index.md
# Wiki - posts/wiki.md or wiki/index.md
# About - about.md or about/index.md
# -----------------------------------
# èœå•é€‰é¡¹å®šåˆ¶ï¼Œä½¿ç”¨ `00ã€01ã€23` ç­‰è¿›è¡Œé€‰é¡¹é¡ºåºè°ƒæ•´
# ğŸ¶ğŸ‰ğŸ‘€ğŸ’¡ğŸ‘“ğŸŒ
[params.menu]
[params.menu.00]
active = true
path = '/nav'
en = 'Nav'
zh = 'å¯¼èˆª'
icon = 'ğŸ¯'
[params.menu.11]
active = true
path = '/posts'
en = 'posts'
zh = 'æ–‡ç« '
icon = 'ğŸ“œ'
[params.menu.22]
active = true
path = '/archive'
en = 'Archive'
zh = 'å½’æ¡£'
icon = 'ğŸ‰'
[params.menu.33]
active = true
path = '/search'
en = 'Search'
zh = 'æœç´¢'
icon = 'ğŸ”'

# é¦–é¡µå›¾ç‰‡/æ–‡å­—
[params.img]
# å¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºå›¾ç‰‡ï¼Œæƒ³æ˜¾ç¤ºä¸€æ®µè¯ï¼Œåªéœ€è¦
# è®¾ç½® `noImgButWords` ä¸º true å³å¯
notImgButWords = false
# å†…ç½®äº† `girl.jpg, wukong.jpg, and tux.jpg`ï¼Œå½“ç„¶ä½ å¯ä»¥
# æŠŠè‡ªå·±å–œæ¬¢å›¾ç‰‡æ”¾åœ¨ `static/imgs/` ç›®å½•ä¸­ï¼Œå¹¶åœ¨ `src` å¼•ç”¨å®ƒï¼Œ
# ä½ è¿˜å¯ä»¥é€šè¿‡ `width` è°ƒæ•´å¼•å…¥å›¾ç‰‡çš„æ˜¾ç¤ºå¤§å°
src = 'greetings.gif'
width = 520
# words = "Stay hungry, Stay foolish. <br>Your time is limited, so don't waste it living someone else's life. <br>Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary. <br>-- Steve Jobs."
# words = "å¤šå°‘äº‹ï¼Œä»æ¥æ€¥ï¼›<br>å¤©åœ°è½¬ï¼Œå…‰é˜´è¿«ã€‚<br>ä¸€ä¸‡å¹´å¤ªä¹…ï¼Œåªäº‰æœå¤•ã€‚<br>-- æ•™å‘˜"
words = "â€œyooooâ€"

[params.contact]
icp = 'çš–ICPå¤‡20001764å·-1'        # å¤‡æ¡ˆå·ï¼Œå¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯
icplink = '//beian.miit.gov.cn' # å¤‡æ¡ˆé“¾æ¥
# weibo = '6867589681'              # e.g. https://weibo.com/u/6867589681
# wechat = 'imgs/bg/wechat.jpg'     # å¾®ä¿¡äºŒç»´ç åœ°å€
# email = 'loveminimal@outlook.com'
github = 'supuwoerc' # e.g. https://github.com/loveminimal
# bilibili = '11608450'             # e.g. https://space.bilibili.com/11608450
# twitter = 'loveminimal'             # e.g. https://twitter.com/loveminimal
# facebook = 'loveminimal'            # e.g. https://facebook.com/loveminimal
# youtube = 'loveminimal'             # e.g. https://youtube.com/user/loveminimal
# telegram = 'https://web.telegram.org/z/'
color = '#696969'             # å›¾æ ‡é¢œè‰²ï¼Œé»˜è®¤ä¸ºæµ…ç°è‰²
slogan = 'Contact me via : )' # è”ç³»æ ‡è¯­ï¼Œä¸æƒ³æ˜¾ç¤ºï¼Œå¯ä»¥ç½®ç©º

# ä»¥ä¸‹ä¸º Markdown è§£ææ“çš„ä¸€äº›è®¾ç½®ï¼Œ
# å»ºè®®ä¿æŒä¸å˜
[markup]
[markup.asciidocExt]
preserveTOC = true
[markup.highlight]
# ä»£ç å—æ˜¾ç¤ºé£æ ¼ã€è¡Œå·æ˜¾ç¤º
style = "github"
lineNos = false
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS", "JSON"]
